# Generated by Django 5.2 on 2025-04-14 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClothingItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('upper', 'UpperWear'), ('lower', 'LowerWear'), ('shoes', 'Shoes'), ('accessory', 'Accessory')], max_length=20)),
                ('type', models.CharField(max_length=50)),
                ('size', models.CharField(max_length=10)),
                ('color', models.CharField(choices=[('red', 'Red'), ('blue', 'Blue'), ('green', 'Green'), ('black', 'Black'), ('white', 'White'), ('yellow', 'Yellow'), ('pink', 'Pink')], max_length=20)),
                ('style', models.CharField(blank=True, max_length=50)),
                ('image', models.ImageField(upload_to='clothing/')),
                ('price', models.IntegerField()),
            ],
        ),
    ]
