# Generated by Django 5.2 on 2025-04-14 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clotheApp', '0003_alter_clothingitem_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothingitem',
            name='image',
            field=models.ImageField(upload_to='clotheApp/static/images'),
        ),
    ]
