# Generated by Django 5.2 on 2025-04-14 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clotheApp', '0004_alter_clothingitem_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothingitem',
            name='image',
            field=models.ImageField(upload_to='static/images'),
        ),
        migrations.AlterField(
            model_name='clothingitem',
            name='size',
            field=models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'X-Large'), ('XXL', 'XX-Large'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11')], max_length=10),
        ),
        migrations.AlterField(
            model_name='clothingitem',
            name='style',
            field=models.CharField(blank=True, choices=[('Casual', 'Casual'), ('Formal', 'Formal'), ('Sports', 'Sports')], max_length=50),
        ),
        migrations.AlterField(
            model_name='clothingitem',
            name='type',
            field=models.CharField(choices=[], max_length=50),
        ),
    ]
