# Generated by Django 5.2 on 2025-04-14 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clotheApp', '0005_alter_clothingitem_image_alter_clothingitem_size_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothingitem',
            name='type',
            field=models.CharField(choices=[('t-shirts', 'T-shirts'), ('shirts', 'Shirts'), ('jackets', 'Jackets'), ('hoodies', 'Hoodies'), ('sweatshirts', 'Sweatshirts'), ('jeans', 'Jeans'), ('trousers', 'Trousers'), ('shorts', 'Shorts'), ('joggers', 'Joggers'), ('capris', 'Capris'), ('casual', 'Casual'), ('boots', 'Boots'), ('sandals', 'Sandals'), ('formal', 'Formal'), ('sports', 'Sports'), ('hats', 'Hats'), ('glasses', 'Glasses'), ('belts', 'Belts'), ('jewelry', 'Jewlery'), ('watches', 'Watches')], max_length=50),
        ),
    ]
