# Generated by Django 5.2 on 2025-04-14 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clotheApp', '0008_alter_clothingitem_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothingitem',
            name='type',
            field=models.CharField(choices=[('T-Shirts', 'T-Shirts'), ('Shirts', 'Shirts'), ('Jackets', 'Jackets'), ('hoodies', 'Hoodies'), ('sweatshirts', 'Sweatshirts'), ('Jeans', 'Jeans'), ('Trousers', 'Trousers'), ('Shorts', 'Shorts'), ('Joggers', 'Joggers'), ('Capris', 'Capris'), ('Casual', 'Casual'), ('Boots', 'Boots'), ('Sandals', 'Sandals'), ('Formal', 'Formal'), ('Sports', 'Sports'), ('Hats', 'Hats'), ('Glasses', 'Glasses'), ('Belts', 'Belts'), ('Jewelry', 'Jewlery'), ('Watches', 'Watches')], max_length=50),
        ),
    ]
