# Generated by Django 5.2 on 2025-04-15 17:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clotheApp', '0009_alter_clothingitem_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='clothingitem',
            name='type',
            field=models.CharField(choices=[('T-Shirts', 'T-Shirts'), ('Shirts', 'Shirts'), ('Jackets', 'Jackets'), ('Hoodies', 'Hoodies'), ('Sweatshirts', 'Sweatshirts'), ('Jeans', 'Jeans'), ('Trousers', 'Trousers'), ('Shorts', 'Shorts'), ('Joggers', 'Joggers'), ('Capris', 'Capris'), ('Casual', 'Casual'), ('Boots', 'Boots'), ('Sandals', 'Sandals'), ('Formal', 'Formal'), ('Sports', 'Sports'), ('Hats', 'Hats'), ('Glasses', 'Glasses'), ('Belts', 'Belts'), ('Jewelry', 'Jewlery'), ('Watches', 'Watches')], max_length=50),
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clotheApp.clothingitem')),
            ],
        ),
    ]
