# Generated by Django 5.2 on 2025-04-04 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Thread_Inn', '0002_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
