# Generated by Django 5.2 on 2025-04-14 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Thread_Inn', '0008_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('men', 'Men'), ('women', 'Women'), ('shoes', 'Shoes'), ('tshirt', 'T-Shirt'), ('kids', 'kids'), ('bottom', 'bottom')], max_length=10),
        ),
    ]
