# Generated by Django 5.2 on 2025-04-15 14:51

import Thread_Inn.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Thread_Inn', '0012_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=Thread_Inn.models.OverwriteStorage(), upload_to='images/'),
        ),
    ]
